### ISSUE TITLE
git checkout not working correctly

### ISSUE THREAD

**Issue by leandroong** [lancethepants/tomatoware#44]
Trying to go back earlier version, using git checkout v1.8 will not compile.

**Comment by lancethepants** [comment]
I bundle all the source for tomatoware in the git repo instead of having to download it every time it's compiled. On occasion I will re-base the repo to get rid of the bloat that accumulates from old package versions. You could probably still compile older versions of tomatoware, but you would have to manually find and download the correct tarball versions for any packages that may have been updated since that revision after a re-base has occurred.
