### ISSUE TITLE
Folder "docs"

### ISSUE THREAD

**Issue by sergeynr** [lancethepants/tomatoware#8]
Hello! What is in the folder "docs" distrib arm-soft-jffs?

**Comment by lancethepants** [comment]
Tomatoware includes the full packages of all the applications and libraries that go into it.  This includes documentation and manuals that are included when compiling and installing, such as the 'man' folder.
I haven't taken the time to selectively determine and remove parts that may be unessential.  Since this project understandably will take up some space, size hasn't been a priority.
The 'docs' folder looks like it is documentation from the berkeley database.

**Comment by sergeynr** [comment]
Thanks
